import pandas as pd
a = pd.read_csv("train.csv")
print(a.head())
print(a.info())
print(a.columns)
print(a.tail())
print(a["Age"])
print(a[["Age", "Survived"]])
print(a[a["Survived"] == 1])
print(a[a["Survived"] == 1])
print(a[a["Sex"] == "female"])
print(a[a["Fare"] >= 100])
print(a[(a["Survived"] == 1) & (a["Sex"] == "female")])
print(a["Sex"].value_counts())
print(a["Survived"].value_counts())
print(a.groupby("Sex")["Survived"].mean())
print(a.groupby("Sex")["Age"].mean())
print(a.groupby("Survived")["Pclass"].mean())
print(a.groupby("Pclass")["Fare"].mean())
print(a.sort_values("Age"))
print(a.sort_values("Fare", ascending = False))
print(a.sort_values("Age", ascending = False).head(1))
a["Age_10"] = a["Age"] + 10
print(a.columns)
print(a[["Name", "Age", "Age_10"]])
a["Fare_2"] = a["Fare"] * 2
print(a.columns)
print(a[["Name", "Fare", "Fare_2"]])
a["Expensive"] = a["Fare"] > 20
print(a.columns)
print(a[["Fare", "Expensive"]])
a["Adult"] = a["Age"] > 18
a["Child"] = a["Age"] < 18
print(a[["Age", "Adult", "Child"]])
print(a.isnull().sum())
print(a.dropna())
a["Age"].fillna(a["Age"].mean(), inplace  =True)
print(a.isnull().sum())
print(a["Age"].min())
print(a["Age"].max())
print(a["Sex"].unique())
